name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install build packages
        run: pip install --upgrade pip build wheel setuptools

      - name: Install editable package
        run: pip install -e ".[dev]"

      - name: Run Pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Run tests
        run: pytest